# Generated by Django 5.0.6 on 2024-07-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_remaining_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='remaining_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
