# Generated by Django 5.0.6 on 2024-07-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0002_contract_birthday_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('expired', 'Expiré'), ('near_expiry', "Proche d'expirer")], default='active', max_length=12),
        ),
    ]
