# Generated by Django 5.0.6 on 2024-07-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0008_alter_contract_contract_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
